### ISSUE TITLE
design mobile results page for devices < 480px

### ISSUE THREAD

**Issue by BenJam** [mysociety/allourideas.org#7]
a la http://www.allourideas.org/studentgovernment/results

**Comment by dracos** [comment]
http://www.tangledindesign.com/blog/deciding-what-responsive-breakpoints-to-use/
http://adactio.com/journal/5425/

**Comment by BenJam** [comment]
@dracos unfortunately these were contractual requirements not necessarily technical standpoints :/

**Comment by BenJam** [comment]
I think we can close this.
